export const hiscores = {
  endpoints: {
    normal: `https://secure.runescape.com/m=hiscore_oldschool/index_lite.ws`,
    ironman: `https://secure.runescape.com/m=hiscore_oldschool_ironman/index_lite.ws`,
    hardcore: `https://secure.runescape.com/m=hiscore_oldschool_hardcore_ironman/index_lite.ws`,
    ultimate: `https://secure.runescape.com/m=hiscore_oldschool_ultimate/index_lite.ws`,
    deadman: `https://secure.runescape.com/m=hiscore_oldschool_deadman/index_lite.ws`,
    seasonal: `https://secure.runescape.com/m=hiscore_oldschool_seasonal/index_lite.ws`,
  },
  activities: [
    "_empty_",
    "league_points",
    "bounty_hunter_hunter",
    "bounty_hunter_rogue",
    "bounty_hunter_hunter_legacy",
    "bounty_hunter_rogue_legacy",
    "clue_scrolls_all",
    "clue_scrolls_beginner",
    "clue_scrolls_easy",
    "clue_scrolls_medium",
    "clue_scrolls_hard",
    "clue_scrolls_elite",
    "clue_scrolls_master",
    "lms_rank",
    "pvp_arena_rank",
    "soul_wars_zeal",
    "rifts_closed"
  ] as const,
  bosses: ["abyssal_sire", "alchemical_hydra", "artio", "barrows_chests",
  "bryophyta", "callisto", "cal'varion", "cerberus",
  "chambers_of_xeric", "chambers_of_xeric_challenge_mode",
  "chaos_elemental", "chaos_fanatic", "commander_zilyana",
  "corporeal_beast", "crazy_archaeologist", "dagannoth_prime",
  "dagannoth_rex", "dagannoth_supreme", "deranged_archaeologist",
  "duke_sucellus", "general_graardor", "giant_mole",
  "grotesque_guardians", "hespori", "kalphite_queen",
  "king_black_dragon", "kraken", "kree'arra", "kril_tsutsaroth",
  "mimic", "nex", "nightmare", "phosani's_nightmare", "obor",
  "phantom_muspah", "sarachnis", "scorpia", "skotizo", "spindel",
  "tempoross", "the_gauntlet", "the_corrupted_gauntlet",
  "the_leviathan", "the_whisperer", "theatre_of_blood",
  "theatre_of_blood_hard_mode", "thermonuclear_smoke_devil",
  "tombs_of_amascut", "tombs_of_amascut_expert_mode", "tzkal-zuk",
  "tztok-jad", "vardorvis", "venenatis", "vet'ion", "vorkath",
  "wintertodt", "zalcano", "zulrah"
] as const,
  gamemodes: [
    "normal",
    "ironman",
    "hardcore",
    "ultimate",
    "deadman",
    "seasonal",
  ] as const,
  skills: [
    "overall",
    "attack",
    "defence",
    "strength",
    "constitution",
    "ranged",
    "prayer",
    "magic",
    "cooking",
    "woodcutting",
    "fletching",
    "fishing",
    "firemaking",
    "crafting",
    "smithing",
    "mining",
    "herblore",
    "agility",
    "thieving",
    "slayer",
    "farming",
    "runecrafting",
    "hunter",
    "construction",
  ] as const,
}
export const grandexchange = {
  endpoints: {
    category: `https://secure.runescape.com/m=itemdb_oldschool/api/catalogue/category.json?`,
    categoryPrice: `https://secure.runescape.com/m=itemdb_oldschool/api/catalogue/items.json?`,
    item: `https://secure.runescape.com/m=itemdb_oldschool/api/catalogue/detail.json?`,
    itemGraph: `https://secure.runescape.com/m=itemdb_oldschool/api/graph`,
  },
}

export default {
  hiscores,
  grandexchange,
}
