export const clan = {
  endpoints: {
    members: `http://services.runescape.com/m=clan-hiscores/members_lite.ws`,
  },
}
export const grandexchange = {
  endpoints: {
    category: `http://services.runescape.com/m=itemdb_rs/api/catalogue/category.json?`,
    categoryItems: `http://services.runescape.com/m=itemdb_rs/api/catalogue/items.json?`,
    item: `http://services.runescape.com/m=itemdb_rs/api/catalogue/detail.json?`,
    itemGraph: `http://services.runescape.com/m=itemdb_rs/api/graph`,
  },
  categories: [
    "Miscellaneous",
    "Ammo",
    "Arrows",
    "Bolts",
    "Construction materials",
    "Construction projects",
    "Cooking ingredients",
    "Costumes",
    "Crafting materials",
    "Familiars",
    "Farming produce",
    "Fletching materials",
    "Food and drink",
    "Herblore materials",
    "Hunting equipment",
    "Hunting produce",
    "Jewellery",
    "Mage armour",
    "Mage weapons",
    "Melee armour - low level",
    "Melee armour - mid level",
    "Melee armour - high level",
    "Melee weapons - low level",
    "Melee weapons - mid level",
    "Melee weapons - high level",
    "Mining and smithing",
    "Potions",
    "Prayer armour",
    "Prayer materials",
    "Range armour",
    "Range weapons",
    "Runecrafting",
    "Runes, Spells and Teleports",
    "Seeds",
    "Summoning scrolls",
    "Tools and containers",
    "Woodcutting product",
    "Pocket items",
    "Stone spirits",
    "Salvage",
    "Firemaking products",
    "Archaeology materials",
    "Wood spirits",
    "Necromancy armour"
  ] as const,
}
export const hiscores = {
  endpoints: {
    normal: `http://services.runescape.com/m=hiscore/index_lite.ws`,
    ironman: `http://services.runescape.com/m=hiscore_ironman/index_lite.ws`,
    hardcore: `http://services.runescape.com/m=hiscore_hardcore_ironman/index_lite.ws`,
  },
  activities: [
    "bounty_hunters",
    "bh_rogues",
    "dominion_tower",
    "the_crucible",
    "castle_wars_games",
    "ba_attackers",
    "ba_defenders",
    "ba_collectors",
    "ba_healers",
    "duel_tournament",
    "mobilising_armies",
    "conquest",
    "fist_of_guthix",
    "gg_resource_race",
    "gg_athletics",
    "we2_armadyl_lifetime_contribution",
    "we2_bandos_lifetime_contribution",
    "we2_armadyl_pvp_kills",
    "we2_bandos_pvp_kills",
    "heist_guard_level",
    "heist_robber_level",
    "cfp_5_game_average",
    "af15_cow_tipping",
    "af15_rats_killed_after_the_miniquest",
    "runescore",
    "clue_scrolls_easy",
    "clue_scrolls_medium",
    "clue_scrolls_hard",
    "clue_scrolls_elite",
    "clue_scrolls_master",
  ] as const,
  gamemodes: ["normal", "ironman", "hardcore"] as const,
  skills: [
    "overall",
    "attack",
    "defence",
    "strength",
    "constitution",
    "ranged",
    "prayer",
    "magic",
    "cooking",
    "woodcutting",
    "fletching",
    "fishing",
    "firemaking",
    "crafting",
    "smithing",
    "mining",
    "herblore",
    "agility",
    "thieving",
    "slayer",
    "farming",
    "runecrafting",
    "hunter",
    "construction",
    "summoning",
    "dungeoneering",
    "divination",
    "invention",
    "archaeology",
    "necromancy"
  ] as const,
}
export const miscellaneous = {
  endpoints: {
    defaultAvatarUrl: `https://secure.runescape.com/m=avatar-rs/default_chat.png?`,
    totalUsers: `https://secure.runescape.com/m=account-creation-reports/rsusertotal.ws`,
  },
}
export const runemetrics = {
  endpoints: {
    profile: `https://apps.runescape.com/runemetrics/profile/profile`,
    monthlyXp: `https://apps.runescape.com/runemetrics/xp-monthly`,
    quests: `https://apps.runescape.com/runemetrics/quests`,
  },
  questStatuses: ["NOT_STARTED", "STARTED", "COMPLETED"] as const,
}

export default {
  clan,
  grandexchange,
  hiscores,
  runemetrics,
  miscellaneous,
}
